### ISSUE TITLE
Separators as line breaks

### ISSUE THREAD

**Issue by fdzhub** [tborychowski/newtab-bookmarks#10]
Hi. For starters, this addon is great. Thanks for making it <3!

As the title says, instead of putting a folder icon with no name, the idea would be to jump to the next row and keep drawing the folders/bookmarks. So, instead of how is [now](https://user-images.githubusercontent.com/17355595/40999332-ef23e8a8-68e0-11e8-9659-b7a6610d721b.png), it could look something like [this](https://user-images.githubusercontent.com/17355595/40999368-0979fbe8-68e1-11e8-8e58-ab1357db7368.png).

I don't know, it could be kinda useful. What do you think?

**Comment by tborychowski** [comment]
Hi,

Ha! To be honest, I forgot about the separators.
I don't have them in my bookmarks, so I never noticed that they even show up (as folders).
They should probably show up as an empty space. I will fix that. (maybe this way you will be able to reproduce your layout).

What you suggest might be a good idea, but the use case is very narrow:
- it will work great in a specific resolution and size of icons & spaces (because they also affect the number of columns).

I'm trying to make it as simple as humanly possible. If you look at Safari's built-in new-tab that displays bookmarks (which inspired this add-on) - it has no settings at all!

Another big problem is that to lay-out the icons I'm using a css grid, and as far as I know it doesn't support this kind of layout. So to make it work I'd have to use some complex calculations with javascript, which would get messy, bug-prone, and difficult to maintain.

I really appreciate your input and idea, but I don't think this is the way I'd like to go.
I hope you understand 😄

**Comment by fdzhub** [comment]
Yeah, totally, maintainability is much more important. No biggie. In any case, I really appreciate the answer and how simple is the add-on. So, cheers!
