### ISSUE TITLE
Visibility on dark backgrounds

### ISSUE THREAD

**Issue by Bjoern-A-Bojesen** [tborychowski/newtab-bookmarks#16]
In New Tab, labels and icons - including the arrow-back icon - tend to disappear against darker backgrounds (such as the random image selected by one of the pre-sets). Would it be possible to fix this somehow, e.g. with a white outline? (On an iPad, for example, any icon can be seen on any background.)

![billede](https://user-images.githubusercontent.com/46493389/50841206-77dadc00-1364-11e9-9677-bb4acde36c9a.png)

**Comment by tborychowski** [comment]
Color of the labels you can change. Color of the icons comes from the icon owners (websites).
If iPad somehow highlights them - it's some sort of internal under-the-hood rendering thing.
They are pngs so no way for me to add nice shadow/outline, preserving the alpha channel (outline would be square around the box the icon is in), and it would look weird.

**Comment by Bjoern-A-Bojesen** [comment]
Ok. Thank you for the quick reply. I realise adding outlines or shadows is more difficult than I thought, thanks for clarifying. I’m glad the label colours can be changed, though - I was not aware of that. That said, you could maybe consider adding a shadow or outline to the arrow (<).

**Comment by tborychowski** [comment]
also - you can add your own CSS to style icons as you wish!

I'm closing this issue as I don't plan to fix it here.
I'm working on a new extension that will be much better than this one (albeit not really compatible, hence a new project, instead of a new version).
Keep an eye on the new project here: https://github.com/tborychowski/perfect-home
