### ISSUE TITLE
[Feature request] Separate homepage from newtab

### ISSUE THREAD

**Issue by spamclassic** [tborychowski/newtab-bookmarks#21]
Thanks for this awesome add-on.
I am not good at English so if you can't understand my word, sorry for that

Can you make option - working in new tab only, homepage only, both?
I want to use this add-on only in new tab page but this add-on doesn't allow me to change homepage.

**Comment by tborychowski** [comment]
Sorry, unfortunately this is not possible (not easily at least).
I need to define what to override in a config file before building the extension, e.g.:
https://github.com/tborychowski/newtab-bookmarks/blob/master/src/manifest.json#L6-L11

So to allow one or the other or both - I would have to produce 3 separate extensions.
Because much more people wished that it overrides both - this is what it does.

You can, however, fork the extension and build it yourself with just the options that you need! :-)
