### ISSUE TITLE
Linux compatibility

### ISSUE THREAD

**Issue by barnscott** [tborychowski/newtab-bookmarks#22]
Does not identify "Bookmarks Menu", "Other Bookmarks", or "Bookmarks toolbar" on Linux. Other folder nested under the "stock" folders do not have issues and work as expected.

![Screenshot from 2019-07-22 21-08-05](https://user-images.githubusercontent.com/48160387/61677331-c0e5f280-acee-11e9-8986-5e08dd5a7d2a.png)

![Screenshot from 2019-07-22 21-27-27](https://user-images.githubusercontent.com/48160387/61678094-70bc5f80-acf1-11e9-9f2c-8828f47be5e7.png)

I tested using Firefox on Fedora as well as using the Fedora's flatpak: https://registry.fedoraproject.org/

I do not have any trouble with Windows implementation.

**Comment by tborychowski** [comment]
Hi!
I'm closing this issue as I don't plan to fix it here.
I'm working on a new extension that will be much better than this one (albeit not really compatible, hence a new project, instead of a new version).

This should be fixed in the new extension.

Keep an eye on the new project here: https://github.com/tborychowski/perfect-home
